
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 06 20:57:28 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 45;
  public static final int MULT = 25;
  public static final int CONST = 7;
  public static final int GRT = 30;
  public static final int GRTEQ = 31;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 41;
  public static final int SEMI = 37;
  public static final int LOWEQ = 33;
  public static final int CONTINUE = 17;
  public static final int MINUS = 24;
  public static final int RPAREN = 42;
  public static final int AND = 34;
  public static final int OR = 35;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 20;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 40;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int LOW = 32;
  public static final int RBRACKET = 46;
  public static final int EQUAL = 36;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int ISEQUAL = 28;
  public static final int NUMBER = 47;
  public static final int MOD = 27;
  public static final int IDENT = 49;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int COLON = 38;
  public static final int FOREACH = 19;
  public static final int LBRACE = 43;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int CHARCONST = 50;
  public static final int WHILE = 10;
  public static final int RBRACE = 44;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int ARR = 22;
  public static final int DEC = 21;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

